# Generated by Django 6.0.6 on 2026-06-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=64, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("address_line_1", models.CharField(max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(db_index=True, max_length=128)),
                ("state", models.CharField(max_length=128)),
                ("postal_code", models.CharField(max_length=32)),
                ("country", models.CharField(max_length=128)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("timezone", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="clinic_clin_is_acti_a183b1_idx"
                    ),
                    models.Index(fields=["city"], name="clinic_clin_city_8cb4a0_idx"),
                ],
            },
        ),
    ]
