# Generated by Django 6.0.6 on 2026-06-27 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("clinic", "0001_initial"),
        ("doctors", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="doctors.doctor",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="time_slots",
                to="clinic.clinic",
            ),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="time_slots",
                to="doctors.doctor",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="time_slot",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointment",
                to="appointments.timeslot",
            ),
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["doctor", "start_at"], name="timeslot_doctor_start_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["clinic", "start_at"], name="timeslot_clinic_start_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["status", "start_at"], name="timeslot_status_start_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="timeslot",
            constraint=models.UniqueConstraint(
                fields=("doctor", "start_at"), name="unique_doctor_timeslot_start"
            ),
        ),
        migrations.AddConstraint(
            model_name="timeslot",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_at__lt", models.F("end_at"))),
                name="timeslot_start_before_end",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "status"], name="appointment_patient_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["doctor", "status"], name="appointment_doctor_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["clinic", "status"], name="appointment_clinic_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["status", "created_at"], name="appointment_status_created_idx"
            ),
        ),
    ]
