# Generated by Django 6.0.6 on 2026-06-27 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinic", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="specialty_name_idx"),
                    models.Index(fields=["is_active"], name="specialty_active_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medical_license_number",
                    models.CharField(max_length=50, unique=True),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "consultation_fee",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specialties",
                    models.ManyToManyField(
                        blank=True, related_name="doctors", to="doctors.specialty"
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="DoctorClinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doctor_memberships",
                        to="clinic.clinic",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinic_memberships",
                        to="doctors.doctor",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["doctor", "is_active"], name="doc_clinic_doc_act_idx"
                    ),
                    models.Index(
                        fields=["clinic", "is_active"], name="doc_clinic_cln_act_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("doctor", "clinic"), name="unique_doctor_clinic"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DoctorSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("slot_duration_minutes", models.PositiveSmallIntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doctor_schedules",
                        to="clinic.clinic",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedules",
                        to="doctors.doctor",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["doctor", "weekday", "is_active"],
                        name="doctor_weekday_active_idx",
                    ),
                    models.Index(
                        fields=["clinic", "weekday", "is_active"],
                        name="clinic_weekday_active_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("start_time__lt", models.F("end_time"))),
                        name="doctor_schedule_start_before_end",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("slot_duration_minutes__gt", 0)),
                        name="doctor_schedule_duration_positive",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(fields=["user"], name="doctor_user_idx"),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["medical_license_number"], name="doctor_license_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(fields=["is_active"], name="doctor_active_idx"),
        ),
    ]
